---
output:
  pdf_document: default
  html_document: default
---

```{r}



```

```{r Install packages}



```

```{r load libraries}
# loading the packages 

library(tidyverse)
library(nbastatR)
library(BasketballAnalyzeR)
library(jsonlite)
library(janitor)
library(extrafont)
library(ggrepel)
library(scales)
library(teamcolors)
library(zoo)
library(future)
library(lubridate)
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)




```

```{r Get Game IDs and Gamelogs data}
selectedSeasons <- c(2010:2022)
# Get game IDs for Regular Season and Playoffs
gameIds_RegSea <- suppressWarnings(seasons_schedule(seasons = selectedSeasons, season_types = "Regular Season") %>% select(idGame, slugMatchup))
gameIds_PlOfs <- suppressWarnings(seasons_schedule(seasons = selectedSeasons, season_types = "Playoffs") %>% select(idGame, slugMatchup))
gameIds_all <- rbind(gameIds_RegSea, gameIds_PlOfs)
# Peek at the game IDs
head(gameIds_all)
tail(gameIds_all)

## Extract game log data for players and teams

# Get player game logs
P_gamelog_regSea <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "player", season_types = "Regular Season"))
P_gamelog_po <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "player", season_types = "Playoffs"))
P_gamelog_all <- rbind(P_gamelog_regSea, P_gamelog_po)
View(head(P_gamelog_all))
View(tail(P_gamelog_all))
# Get team game logs
T_gamelog_regSea <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "team", season_types = "Regular Season"))
T_gamelog_po <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "team", season_types = "Playoffs"))
T_gamelog_all <- rbind(T_gamelog_regSea, T_gamelog_po)
view(head(T_gamelog_all))
View(tail(T_gamelog_all))

```

```{r}
View(head(gameIds_all))
View(tail(gameIds_all))

str(T_gamelog_all)
summary(T_gamelog_all)


```

```{r}
### Create player and team box scores
########
# Create Tbox (Team box score) per season
Tbox_all <- T_gamelog_all %>%
  group_by("Season"=yearSeason, "Team"=slugTeam) %>%
  dplyr::summarise(GP=n(), MIN=sum(round(minutesTeam/5)),
                   PTS=sum(ptsTeam),
                   W=sum(outcomeGame=="W"), L=sum(outcomeGame=="L"),
                   P2M=sum(fg2mTeam), P2A=sum(fg2aTeam), P2p=P2M/P2A,
                   P3M=sum(fg3mTeam), P3A=sum(fg3aTeam), P3p=P3M/P3A,
                   FTM=sum(ftmTeam), FTA=sum(ftaTeam), FTp=FTM/FTA,
                   OREB=sum(orebTeam), DREB=sum(drebTeam), AST=sum(astTeam),
                   TOV=sum(tovTeam), STL=sum(stlTeam), BLK=sum(blkTeam),
                   PF=sum(pfTeam), PM=sum(plusminusTeam)) %>%
  as.data.frame()
# Create Obox (Opponent Team box score) per season
Obox_all <- T_gamelog_all %>%
  group_by("Season"=yearSeason, "Team"=slugOpponent) %>%
  dplyr::summarise(GP=n(), MIN=sum(round(minutesTeam/5)),
                   PTS=sum(ptsTeam),
                   W=sum(outcomeGame=="L"), L=sum(outcomeGame=="W"),
                   P2M=sum(fg2mTeam), P2A=sum(fg2aTeam), P2p=P2M/P2A,
                   P3M=sum(fg3mTeam), P3A=sum(fg3aTeam), P3p=P3M/P3A,
                   FTM=sum(ftmTeam), FTA=sum(ftaTeam), FTp=FTM/FTA,
                   OREB=sum(orebTeam), DREB=sum(drebTeam), AST=sum(astTeam),
                   TOV=sum(tovTeam), STL=sum(stlTeam), BLK=sum(blkTeam),
                   PF=sum(pfTeam), PM=sum(plusminusTeam)) %>%
  as.data.frame()
# Create Pbox (Player box score) per season
Pbox_all <- P_gamelog_all %>%
  group_by("Season"=yearSeason, "Team"=slugTeam, "Player"=namePlayer) %>%
  dplyr::summarise(GP=n(), MIN=sum(minutes), PTS=sum(pts),
                   P2M=sum(fg2m), P2A=sum(fg2a), P2p=100*P2M/P2A,
                   P3M=sum(fg3m), P3A=sum(fg3a), P3p=100*P3M/P3A,
                   FTM=sum(ftm), FTA=sum(fta), FTp=100*FTM/FTA,
                   OREB=sum(oreb), DREB=sum(dreb), AST=sum(ast),
                   TOV=sum(tov), STL=sum(stl), BLK=sum(blk),
                   PF=sum(pf)) %>%
  as.data.frame()


```

```{r}
View(Tbox_all[Tbox_all$Team=="GSW",])
View(Obox_all[Obox_all$Team=="GSW",])

```

```{r}

View(Pbox_all[Pbox_all$Player=="Stephen Curry",])


```

```{r}
## Use Regular Season data
#####################
# Create Tbox (Team box score) for each Regular Season
Tbox <- T_gamelog_regSea %>%
  group_by("Season"=yearSeason, "Team"=slugTeam) %>%
  dplyr::summarise(GP=n(), MIN=sum(round(minutesTeam/5)),
                   PTS=sum(ptsTeam),
                   W=sum(outcomeGame=="W"), L=sum(outcomeGame=="L"),
                   P2M=sum(fg2mTeam), P2A=sum(fg2aTeam), P2p=P2M/P2A,
                   P3M=sum(fg3mTeam), P3A=sum(fg3aTeam), P3p=P3M/P3A,
                   FTM=sum(ftmTeam), FTA=sum(ftaTeam), FTp=FTM/FTA,
                   OREB=sum(orebTeam), DREB=sum(drebTeam), AST=sum(astTeam),
                   TOV=sum(tovTeam), STL=sum(stlTeam), BLK=sum(blkTeam),
                   PF=sum(pfTeam), PM=sum(plusminusTeam)) %>%
  as.data.frame()
# Create Obox (Opponent Team box score) for each Regular Season
Obox <- T_gamelog_regSea %>%
  group_by("Season"=yearSeason, "Team"=slugOpponent) %>%
  dplyr::summarise(GP=n(), MIN=sum(round(minutesTeam/5)),
                   PTS=sum(ptsTeam),
                   W=sum(outcomeGame=="L"), L=sum(outcomeGame=="W"),
                   P2M=sum(fg2mTeam), P2A=sum(fg2aTeam), P2p=P2M/P2A,
                   P3M=sum(fg3mTeam), P3A=sum(fg3aTeam), P3p=P3M/P3A,
                   FTM=sum(ftmTeam), FTA=sum(ftaTeam), FTp=FTM/FTA,
                   OREB=sum(orebTeam), DREB=sum(drebTeam), AST=sum(astTeam),
                   TOV=sum(tovTeam), STL=sum(stlTeam), BLK=sum(blkTeam),
                   PF=sum(pfTeam), PM=sum(plusminusTeam)) %>%
  as.data.frame()
# Create Pbox (Player box score) for each Regular Season
Pbox <- P_gamelog_regSea %>%
  group_by("Season"=yearSeason, "Team"=slugTeam, "Player"=namePlayer) %>%
  dplyr::summarise(GP=n(), MIN=sum(minutes), PTS=sum(pts),
                   P2M=sum(fg2m), P2A=sum(fg2a), P2p=100*P2M/P2A,
                   P3M=sum(fg3m), P3A=sum(fg3a), P3p=100*P3M/P3A,
                   FTM=sum(ftm), FTA=sum(fta), FTp=100*FTM/FTA,
                   OREB=sum(oreb), DREB=sum(dreb), AST=sum(ast),
                   TOV=sum(tov), STL=sum(stl), BLK=sum(blk),
                   PF=sum(pf)) %>%
  as.data.frame()
View(Pbox[Pbox$Player=="Stephen Curry",])


```

```{r}
??nbastatR
library(tidyverse)
library(nbastatR)
library(BasketballAnalyzeR)
library(jsonlite)
library(janitor)
library(extrafont)
library(ggrepel)
library(scales)
library(teamcolors)
library(zoo)
library(future)
library(lubridate)
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)


library(dplyr)


```

```{r}
# Barline plots
#####################
tmSelected <- "GSW"
Pbox.sel <- subset(Pbox, Team==tmSelected &
                    MIN>=1000)
seasonSelected <- 2022
barline(data=Pbox.sel[Pbox.sel$Season==seasonSelected,], id="Player",
        bars=c("P2M","P3M","FTM"), line="PTS",
        order.by="PTS", labels.bars=c("2PM","3PM","FTM"),
        title=tmSelected)

```

```{r}
# Scatter plots
#####################
tmSelected <- "GSW"
Pbox.sel <- subset(Pbox, Team==tmSelected & MIN>=1000)
attach(Pbox.sel)
X <- data.frame(AST, TOV, PTS)/MIN
detach(Pbox.sel)
mypal <- colorRampPalette(c("blue","green","red"))
scatterplot(X, data.var=c("AST","TOV"), z.var="PTS",
            labels=paste(Pbox.sel$Player,", ",Pbox.sel$Season), palette=mypal)
scatterplot(X, data.var=c("AST","TOV"), z.var="PTS",
            labels=paste(Pbox.sel$Player,", ",Pbox.sel$Season), palette=mypal,
            zoom=c(0.08,0.16,0.05,0.10))

```

```{r}
# Bubble plots
#####################

tmSelected <- "GSW"
seasonSelected <- 2022
Tbox.sel <- subset(Tbox_all,Season==seasonSelected)

attach(Tbox.sel)
X <- data.frame(T=Team, P2p, P3p, FTp, AS=P2A+P3A+FTA)
detach(Tbox.sel)
labs <- c("2-point shots (% made)",
          "3-point shots (% made)",
          "free throws (% made)",
          "Total shots attempted")
bubbleplot(X, id="T", x="P2p", y="P3p", col="FTp",
           size="AS", labels=labs)

tmSelected <- c("GSW", "BOS", "MIA", "DAL")
seasonSelected <- 2022
Pbox.sel <- subset(Pbox, Team %in% tmsSelected & MIN>=1500 & Season==seasonSelected)
                   
attach(Pbox.sel)
X <- data.frame(ID=Player, Team, V1=DREB/MIN, V2=STL/MIN,
                V3=BLK/MIN, V4=MIN)
detach(Pbox.sel)
labs <- c("Defensive Rebounds","Steals","Blocks",
          "Total minutes played")
bubbleplot(X, id="ID", x="V1", y="V2", col="V3",
           size="V4", text.col="Team", labels=labs,
           title=paste0("NBA Players in ", seasonSelected),
           text.legend=TRUE, text.size=3.5, scale=FALSE)
```

```{r}


```

```{r}
View(tail(T_gamelog_all))


```

```{r}


??PbP

```

```{r}
# K-means clustering of NBA teams
#####################
seasonSelected <- 2022
Tbox.sel <- subset(Tbox_all,Season==seasonSelected)
Obox.sel <- subset(Obox_all,Season==seasonSelected)
FF <- fourfactors(Tbox.sel,Obox.sel)
OD.Rtg <- FF$ORtg/FF$DRtg
F1.r <- FF$F1.Off/FF$F1.Def
F2.r <- FF$F2.Def/FF$F2.Off
F3.Off <- FF$F3.Off
F3.Def <- FF$F3.Def
P3M.ff <- Tbox.sel$P3M
STL.r <- Tbox.sel$STL/Obox.sel$STL
data <- data.frame(OD.Rtg, F1.r, F2.r, F3.Off, F3.Def, P3M.ff, STL.r)
RNGkind(sample.kind="Rounding")
set.seed(29)
kclu1 <- kclustering(data)
plot(kclu1)
set.seed(29)
kclu2 <- kclustering(data, labels=Tbox.sel$Team, k=7)
plot(kclu2)
kclu2.W <- tapply(Tbox.sel$W, kclu2$Subjects$Cluster, mean)
cluster <- as.factor(kclu2$Subjects$Cluster)
Xbubble <- data.frame(Team=Tbox.sel$Team, PTS=Tbox.sel$PTS,
                      PTS.Opp=Obox.sel$PTS, cluster,
                      W=Tbox.sel$W)
labs <- c("PTS", "PTS.Opp", "cluster", "Wins")
bubbleplot(Xbubble, id="Team", x="PTS", y="PTS.Opp",
           col="cluster", size="W", labels=labs,
           title=paste0("NBA Team Clusters - ",seasonSelected))


```

```{r}
## Hierarchical clustering of NBA players
#####################
#select seasons to analyze
seasonSelected <- c(2020, 2021, 2022)
#filter the player boxscores dataset to include the seasons we selected before and select the top 100 players in points scored
Pbox.sel <- Pbox %>% filter(Season %in% seasonSelected) %>% slice_max(PTS, n = 100)
#attach the player boxscores dataset from above
attach(Pbox.sel)
#create a data frame that contains the columns/stats that we want to use to cluster players
data <- data.frame(PTS, P3M, REB=OREB+DREB,
                   AST, TOV, STL, BLK, PF)
#detach the player box scores dataset
detach(Pbox.sel)
#create the ID variable to annotate each data point, which is essentially the player name, their team, and season
ID <- paste0(Pbox.sel$Player,"-",Pbox.sel$Team,", ", Pbox.sel$Season)
#run the hierarchical clustering algorithm
hclu1 <- hclustering(data)
#plot the algorithm to choose the optimal number of clusters.
plot(hclu1)
#run the hierarchical clustering algorithm, adding the IDs and opting for 5 clusters
hclu2 <- hclustering(data, labels=ID, k=5)
#show the radar plot of each cluster
plot(hclu2, profiles=TRUE)
#plot the dendrogram
plot(hclu2, rect=TRUE, labels=ID, cex.labels=0.75)
### Variability of the clusters
#create a player box score subset, containing only players that had played over 1,000 minutes
Pbox.subset <- subset(Pbox.sel, MIN>=1000)
#define MIN
MIN <- Pbox.subset$MIN
#create a data frame with the player clusters, scaling the data and adding the minutes played
X <- data.frame(hclu2$Subjects, scale(data), MIN)
#select the variables we want to see the variability for
dvar <- c("PTS","P3M","REB","AST",
          "TOV","STL","BLK","PF")
#select the variable to use as the size
svar <- "MIN"
yRange <- range(X[,dvar])
quant <- quantile(x = X$MIN, type = 3)
sizeRange <- c(quant[[1]], quant[[5]])
#define the number of clusters
no.clu <- 5
p <- vector(no.clu, mode="list")
for (k in 1:no.clu) {
  XC <- subset(X, Cluster==k)
  vrb <- variability(XC[,3:11], data.var=dvar,
                     size.var=svar, weight=FALSE,
                     VC=FALSE)
  title <- paste("Cluster", k)
  p[[k]] <- plot(vrb, size.lim=sizeRange, ylim=yRange,
                 title=title, leg.pos=c(0,1),
                 leg.just=c(-0.5,0),
                 leg.box="vertical",
                 leg.brk=seq(quant[[1]],quant[[5]],(quant[[5]]-quant[[1]])/5),
                 leg.title.pos="left", leg.nrow=1,
                 max.circle=7)
}
library(gridExtra)
grid.arrange(grobs=p, ncol=3)
View(X)

```

```{r}


```
